### ISSUE TITLE
Missing area in Wales heatmap

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantvis#151]
When looking at district heatmap in Wales, the district Rhondda, Cynon, Taff appears in the list with grants, but the heatmap shows 0 grants

https://insights.threesixtygiving.org/data?countries=W92000004

![image](https://user-images.githubusercontent.com/20462640/173032683-b323613f-7c25-4407-a660-7a42467d66e7.png)

The issue also exists if you open a GrantNav filtered search for this district https://grantnav.threesixtygiving.org/search?query=%2A&default_field=%2A&sort=_score+desc&recipientRegionName=Wales&recipientDistrictName=Rhondda+Cynon+Taf+-+Rhondda+Cynon+Taf

The geocode is W06000016 - which seems to be marked as [inactive in FindthatPostcode](https://findthatpostcode.uk/areas/W06000016.html), but it's showing as [live in the ONS site](https://statistics.data.gov.uk/atlas/resource?uri=http%3A%2F%2Fstatistics.data.gov.uk%2Fid%2Fstatistical-geography%2FW06000016&inactive=false). Could that be causing an issue?

**Comment by mariongalley** [comment]
David found an issue in FindThatPostcode related to the same region. He said:

> I've diagnosed the find-that-postcode issue here: https://github.com/drkane/find-that-postcode/issues/27 - I don't think it's related to the insights issue, although it's a fairly big coincedence if it isn't.

**Comment by KDuerden** [comment]
I just checked and no other local authority areas are affected, so it is just Rhondda, Cynon, Taff which has issues.

**Comment by michaelwood** [comment]
Yeah this is likely because of a geo name matching issue. 

In our geo data we have 
```'Rhondda Cynon Taf', LAD20CD: 'W06000016'```

and In the grant data we have

```Rhondda, Cynon, Taff: {grantCount: 1541, areaId: 'W06000016'}```

We do area name based matching instead of id based matching (matching between grant and geo shape) because this allows the code to not need to care what field the Id comes from (e.g. region. country, la.. etc).. which is fine until we hit this edge case where the name no longer matches...

https://grantnav.threesixtygiving.org/grant/360G-cabinetoffice-GA-076705 -> Show additional data:
```
additional_data: recipientOrganizationLocation: laua	W06000016
additional_data: recipientOrganizationLocation: laua_name	Rhondda, Cynon, Taff
```

Not quite sure where this could be fixed yet. Or if it is a matter of updating the lookup data.

**Comment by michaelwood** [comment]
Ah slightly more complicated, https://findthatpostcode.uk/areas/W06000016.json

```json
     "name": "Rhondda, Cynon, Taff",
      "name_welsh": "Rhondda Cynon Taf",
```

**Comment by michaelwood** [comment]
@drkane Is there a version of the [laut.geojson](https://github.com/ThreeSixtyGiving/insights-ng/blob/live/insights/static/geo/uncompressed/laut.geojson) file that uses the English(?) CTYUA20NM name? I'm not sure where those files originate from.

**Comment by michaelwood** [comment]
Looks like 'Rhondda Cynon Taf' is the name used in https://data.gov.uk/dataset/cd97a8df-e2fe-4f3d-a60f-1f871a317d31/counties-and-unitary-authorities-december-2016-full-extent-boundaries-in-england-and-wales

**Comment by drkane** [comment]
I think what's happened is that there was a name change for the local authority, but the way find that postcode imports the source data means that the old name is stored rather than the new one (which is also why it's showing as inactive). So that's the one that's picked up in the geonames data here.

In terms of boundaries the latest version is this one: https://geoportal.statistics.gov.uk/datasets/ons::counties-and-unitary-authorities-december-2021-uk-buc/explore?location=55.173100%2C-3.316413%2C7.17 - we can probably pick up a geojson version of that. Or the [2020 version](https://geoportal.statistics.gov.uk/datasets/ons::counties-and-unitary-authorities-december-2020-uk-buc/explore?location=55.173100%2C-3.316413%2C7.17) might fit better with the current code.

**Comment by michaelwood** [comment]
So yeah, Insights uses the data from https://findthatpostcode.uk/areas/W06000016.json to get the name from the LAD20CD in the grant (`W06000016`). So if https://findthatpostcode.uk/areas/W06000016.json name field were updated to use "Rhondda Cynon Taf" it would then match the name in the geojson data and we can associate the grant data again.

**Comment by mariongalley** [comment]
@drkane Is it possible to apply a fix in FindThatPostcode? And if so, will it automatically resolve the issue in Insights?

**Comment by drkane** [comment]
This issue is now fixed in findthatpostcode and os the name in <https://findthatpostcode.uk/areas/W06000016.json> is now "Rhondda Cynon Taf". I think Insights might need to re-import the names of the areas in order to fix the issue?

**Comment by michaelwood** [comment]
Thanks @drkane. That has resolved it for me. @KDuerden @mariongalley closing for now - feel free to re-open this if I've missed something. Thanks
