### ISSUE TITLE
Map insights filter query to grantnav query

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#16]
Map the query string from insights to GranNav

| Insights-NG         | GrantNav                    |
|---------------------|-----------------------------|
|                     | currency                    |
| awardAmount.min,max | amountAwarded               |
| awardDates.min,max  | awardDate,min_date,max_date |
| area                | recipientRegionName         |
| area                | recipientDistrictName       |
| funderTypes         | fundingOrganizationTSGType  |
| funders             | fundingOrganization         |
| grantProgrammes     | grantProgramme              |
|                     | recipientOrganization       |
| orgtype             | n/a                         |

e.g.

http://localhost:5000/data?area=E12000004&funders=360G-ThriveLDN
-> 
https://grantnav.threesixtygiving.org/search?query=%2A&default_field=%2A&sort=_score+desc&recipientRegionName=North%20West&fundingOrganization=360G-ThriveLDN

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Map insights filter query to grantnav query](https://trello.com/c/m41FD8vI/20-map-insights-filter-query-to-grantnav-query)

**Comment by Bjwebb** [comment]
I've started constructing the GrantNav query within Insights-NG for a limited number of filters: https://github.com/ThreeSixtyGiving/insights-ng/compare/dev...16-insights-grantnav

I've matched up all the filters on Insights-NG and GrantNav, in the table below. Most of them present problems, because one site doesn't implement them, or implements them in a more restricted way:

| Insights-NG             | GrantNav                    | Notes                                                      |
|-------------------------|-----------------------------|------------------------------------------------------------|
|                         | currency                    | No such filter in Insights-NG                              |
| awardAmount.min,max     | amountAwarded               | GrantNav doesn't allow arbitrary values, only fixed bands. |
| awardDates.min,max      | awardDate,min_date,max_date | GrantNav only allows years or months, not specific days    |
| area (area/regions)     | recipientRegionName         | TODO: need to look up the name from the code               |
| area (localAuthorities) | recipientDistrictName       | TODO: need to look up the name from the code               |
| area (countries)        |                             | No such filter in GrantNav                                 |
| funderTypes             | fundingOrganizationTSGType  | Done                                                       |
| funders                 | fundingOrganization         | Done                                                       |
| grantProgrammes         | grantProgramme              | Done                                                       |
|                         | recipientOrganization       | No such filter in Insights-NG                              |
| orgtype                 |                             | No such filter in GrantNav                                 |

**Comment by michaelwood** [comment]
Currency - we don't need to worry about this at the moment there is a currently a notice on insights that says "This data contains grants made in 2 different currencies. Only showing grants made in GBP. From the 360Giving data registry" .

awardAmount  -  GN should work with &min_amount=50&max_amount=800 for arbitrary amounts (it has an "Apply" button next to it on the interface) . It would be good to standardise the bands to match GN but that's not priority.

awardDates.min,max - Can drop support for specific Day in insights

area (countries) - We should be able to add this to GN ( https://github.com/ThreeSixtyGiving/insights-ng/blob/dev/insights/commands/fetch_data.py#L125 ) by adding the `additional_data` field.

recipientOrganization - I think we can add this to Insights without too much difficulty.

orgtype -  We should be able to add this to GN ( https://github.com/ThreeSixtyGiving/insights-ng/blob/dev/insights/commands/fetch_data.py#L133 ) by adding the `additional_data` field.

**Comment by michaelwood** [comment]
From discussions:

Using URLSearchParams();
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams


Some
 WIP  for awarddate, not sure if we want to use that month type as it might not be supported by all browsers, possibly just a select or freeform 


```diff
           <filter-item title="Award date">
             <label for="award-date-min">From</label>
-            <input id="award-date-min" type="date" class="filter-input" v-model="filters.awardDates.min">
+            <input id="award-date-min" type="month" class="filter-input" v-model="filters.awardDates.min">
             <label for="award-date-max">to</label>
-            <input id="award-date-max" type="date" class="filter-input" v-model="filters.awardDates.max">
+            <input id="award-date-max" type="month" class="filter-input" v-model="filters.awardDates.max">
           </filter-item>


```

Some WIP/hint on recipient filtering, this isn't tested and should be recipients rather than recipient.

```diff
diff --git a/insights/static/js/data-display.js b/insights/static/js/data-display.js
index 077f20c..99ea18f 100644
--- a/insights/static/js/data-display.js
+++ b/insights/static/js/data-display.js
@@ -42,6 +42,7 @@ function initialFilters(useQueryParams) {
     areas.push(...params.getAll("area"));
 
     return {
+        recipient: params.getAll("recipient"),
         awardAmount: {
             min: params.get("awardAmount.min"),
             max: params.get("awardAmount.max"),
@@ -124,7 +125,7 @@ var app = new Vue({
                 if (filters[field].min === '') { filters[field].min = null; }
                 if (filters[field].max === '') { filters[field].max = null; }
             });
-            ['area', 'orgtype', 'grantProgrammes', 'funders', 'funderTypes'].forEach((field) => {
+            ['area', 'orgtype', 'recipient', 'grantProgrammes', 'funders', 'funderTypes'].forEach((field) => {
                 filters[field] = filters[field].map((item) => typeof item=="string" ? item : item.value );
                 if (Array.isArray(BASE_FILTERS[field])) {
                     filters[field] = filters[field].concat(BASE_FILTERS[field]);
```

```diff
diff --git a/insights/schema.py b/insights/schema.py
index bcafddf..2316ef7 100644
--- a/insights/schema.py
+++ b/insights/schema.py
@@ -419,6 +419,12 @@ def get_grants_base_query(query, **kwargs):
             GrantModel.insights_org_latest_income
             <= kwargs.get("org_size", {}).get("max"),
         )
+
+    if kwargs.get("recipient"):
+        query = query.filter(
+            GrantModel.insights_org_id.in_(kwargs.get("recipient")),
+        )
+
     # if kwargs.get("org_age", {}).get("min"):
     #     query = query.filter(
     #         GrantModel.recipientOrganization_ageAtGrant >= kwargs.get(
```

**Comment by Bjwebb** [comment]
Current status:




| Insights-NG             | GrantNav                            | Notes                                                                       |
|-------------------------|-------------------------------------|-----------------------------------------------------------------------------|
|                         | currency                            | Missing in Insights, but the interface is sufficiently clear about what's happened. |
| awardAmount.min,max     | amountAwarded,min_amount,max_amount | Done                                                                        |
| awardDates.min,max      | awardDate,min_date,max_date         | TODO: restrict Insights to months, rather than specific days. |
| area (area/regions)     | recipientRegionName                 | Done, but at least one name doesn't quite match: "Yorkshire and The Humber" |
| area (localAuthorities) | recipientDistrictName               | LA names are not the same between the 2 tools, e.g. "City of Bristol" vs "Bristol, City of" |
| area (countries)        |                                     | TODO: add this to GrantNav |
| funderTypes             | fundingOrganizationTSGType          | Done                                                                        |
| funders                 | fundingOrganization                 | Done                                                                        |
| grantProgrammes         | grantProgramme                      | Done                                                                        |
| recipients              | recipientOrganization               | Done                                                                        |
| orgtype                 |                                     | TODO: add this to GrantNav |

District and Region names don't match between Insights and GrantNav. e.g. "Brighton and Hove" vs "The City of Brighton and Hove". I've not yet done any looking into why this is.

**Comment by Bjwebb** [comment]
So, it looks like the names of areas are coming from quite different sources.

In Insights they come from https://findthatpostcode.uk/ which is run by David Kane, and I think [pulls them from](https://findthatpostcode.uk/about#data-sources) the Office for National Statistics (ONS) [Register of Geographic Codes](https://geoportal.statistics.gov.uk/datasets/register-of-geographic-codes-june-2019-for-the-united-kingdom/about). In Insights, this data is kept in the database.

In GrantNav and the datastore they are [manually extracted from Doc/Codelist.xlsx within Ordnance Survey (OS) Code-Point Open](https://github.com/ThreeSixtyGiving/grantnav/#fetching-external-datasets). The data is stored in a codelist.csv file in both the [datastore](https://github.com/ThreeSixtyGiving/datastore/blob/master/datastore/additional_data/sources/data_files/codelist.csv) and [GrantNav](https://github.com/ThreeSixtyGiving/grantnav/blob/master/dataload/codelist.csv) repos.

Not all of these are up to date, but I've checked the latest version of the source data, and they also differ.

**Comment by Bjwebb** [comment]
Looks like the value of `orgtype` relies on a bit of custom code https://github.com/ThreeSixtyGiving/insights-ng/blob/live/insights/commands/fetch_data.py#L178-L191. If we want to reproduce this in GrantNav, would it be best to move this into the datastore? I guess the alternative would be not to support GrantNav links if an orgtype is selected.

**Comment by Bjwebb** [comment]
Current status:

| Insights-NG             | GrantNav                            | Notes                                                                       |
|-------------------------|-------------------------------------|-----------------------------------------------------------------------------|
| awardAmount.min,max     | amountAwarded,min_amount,max_amount | Done                                                                        |
| awardDates.min,max      | awardDate,min_date,max_date         | Ongoing work in this PR https://github.com/ThreeSixtyGiving/insights-ng/pull/40 |
| area (area/regions)     | recipientRegionName                 | Waiting on a GrantNav deploy of https://github.com/ThreeSixtyGiving/grantnav/pull/815 |
| area (localAuthorities) | recipientDistrictName               |  Waiting on a GrantNav deploy of https://github.com/ThreeSixtyGiving/grantnav/pull/815 |
| area (countries)        |                                     | Waiting on a GrantNav deploy of https://github.com/ThreeSixtyGiving/grantnav/pull/815 |
| funderTypes             | fundingOrganizationTSGType          | Done                                                                        |
| funders                 | fundingOrganization                 | Done                                                                        |
| grantProgrammes         | grantProgramme                      | Done                                                                        |
| recipients              | recipientOrganization               | Done                                                                        |
| orgtype                 |                                     | Don't link to GrantNav if this filter is specified |
