### ISSUE TITLE
Add Insights results page charts to Insights homepage (all grants view)

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#169]
Successor to #158 

Add the charts that are currently available on the Results page but not the Homepage to the Homepage. These are: Recipient type, Latest income of charity recipients and Age of recipient organisations, Award date.

**Comment by codemacabre** [comment]
@mariongalley After investigating this, it turns out that the best option may be to reuse the data-display page to present the charts on the homepage, as refactoring the existing code on the homepage will require quite a lot of customisation to get the charts in the correct order and displaying correctly, which will essentially duplicate how the data display page works.

I propose we *remove* the homepage and instead route the homepage `/` to the data display page (this will maintain backwards compatibility and won't break any links, so `/` and `/data` will still work). By removing filters on page load, it'll display all grants as on the current homepage but all charts as on the data-display page.

This could contribute to future performance improvements and would improve maintainability by **halving the codebase**! However I wanted to check with you first in case you had any specific plans for maintaining a discrete page for the homepage? If not, are you happy for me to proceed with pruning the code down?

**Comment by mariongalley** [comment]
@codemacabre I guess it depends what the Homepage does that the results page doesn't? In my mind they're more or less the same page, but I don't know if there's functionality or design elements on the homepage that we would lose if we did this.

We do have plans in future for a discrete homepage which signposts to a variety of dashboards including the Cost of Living Tracker, Covid Tracker, future trackers including Grants to Individuals and DEI. There's a question mark for me about whether that page would have any visualisations on it or merely be copy and links elsewhere.

**Comment by codemacabre** [comment]
@mariongalley They do much the same thing, but in different ways. Removing the existing homepage and proceeding as described wouldn't lose any functionality, and from your description of a future homepage, it seems like this is likely to be needed then anyway.

**Comment by mariongalley** [comment]
@codemacabre If @michaelwood is happy with it then I say go ahead!

Created a new ticket #174 for the non-clickable charts too

**Comment by michaelwood** [comment]
Yes I think the proposal sounds good. Any simplification of the code base will also help with the custom dashboard type work
