### ISSUE TITLE
Include separate count for recipient types in headline stats 

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#180]
This would look like this, we need to force a min height on the headline stat boxes to make sure they all align.

![image](https://user-images.githubusercontent.com/493697/223158772-6fd5c69c-50aa-4976-80c9-18b7a20096cf.png)

**Comment by mariongalley** [comment]
@michaelwood Fine with the min height but I do think that headline stats do look a bit too close to the top of the boxes? I appreciate they can't be vertically middle-adjusted because some boxes have more lines of content than others, but if the stat within each box could be roughly the equivalent height that it *would* be if the boxes with the most content *were* middle-adjusted, that would be preferable (sorry I couldn't work out a less convoluted way of explaining!).

**Comment by mariongalley** [comment]
@KDuerden This could look better with a 6th stat like the quality dashboard has. Is there another that it might be useful to include?

**Comment by KDuerden** [comment]
> This could look better with a 6th stat like the quality dashboard has. Is there another that it might be useful to include?

I don't have anything to suggest off the top of my head. We deliberately removed the average figure when adding the funder count, and I wouldn't advocate adding it back.

**Comment by mariongalley** [comment]
@michaelwood I don't think there is a suitable 6th headline stat - please can you revisit the padding/alignment on the assumption there will be 5 stats?

**Comment by mariongalley** [comment]
This is done
