### ISSUE TITLE
Add  "Based on X grants." to clarify what's in the charts

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#207]

**Comment by mariongalley** [comment]
Also doesn't specify which grants couldn't be included - copy for e.g.

Based on 825,816 grants.

126,947 grants did not have enough information to determine geography.

**Comment by michaelwood** [comment]
I've pushed a fixed for this with some more consistent copy on the number of grants not included in the chart/map.

Do we still want "Based on xyz", to me "Based on" creates some unspecified uncertainty as to why this number is different/being repeated from the total?

**Comment by mariongalley** [comment]
@michaelwood Thanks, I'm satisfied that "X grants are not shown as they did not include information to determine Y" is sufficient and we don't also need it to say "Based on Z grants". At least if `Z = Total grants - X` and therefore doesn't provide any new information. If it is sometimes not that number I'd love to understand why and consider displaying it (but agree we could use different language like "This chart shows data from Z grants").

@KDuerden any objections?

**Comment by KDuerden** [comment]
It looks like that copy is fixed, which is confusing if you have data filtered.

Eg this view had only 367 grants in the filter but still says this.

![image](https://github.com/ThreeSixtyGiving/360insights/assets/20462640/b28169cf-ace2-4438-8d83-41e424ccaac6)

**Comment by KDuerden** [comment]
Maybe out of scope - but I was just thinking it would be useful to know how many grants are showing, as well as how many aren't at all times. Is there any scope for this to appear dynamically in place of the (number of grants) part of the titles?

For example this filter has [5,126 grants](http://insights-test.360dokku1.vs.mythic-beasts.com/?recipientDistrictName=Belfast), so in the charts where there is data for every grant it says eg

![image](https://github.com/ThreeSixtyGiving/360insights/assets/20462640/b77ce7c8-44d4-4c53-9474-bb1970dc02e8)


But for other graphs it gives the total shown in the chart in that title, as otherwise you need to do maths, and for large numbers you only get an approx grant total at the top anyway.

![image](https://github.com/ThreeSixtyGiving/360insights/assets/20462640/d960253c-3e1e-43d0-ae64-780a0e5613fc)

**Comment by michaelwood** [comment]
> It looks like that copy is fixed, which is confusing if you have data filtered.
> 
> Eg this view had only 367 grants in the filter but still says this.
> 
> ![image](https://private-user-images.githubusercontent.com/20462640/289020481-b28169cf-ace2-4438-8d83-41e424ccaac6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTI0NDksIm5iZiI6MTcwMjM5MjE0OSwicGF0aCI6Ii8yMDQ2MjY0MC8yODkwMjA0ODEtYjI4MTY5Y2YtYWNlMi00NDM4LThkODMtNDFlNDI0Y2NhYWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE0NDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZDk5ZDQ1MmFmMWQ2ZGZkZjY1M2Y4MzdiNTIxNjBkOGI3ZjAxYzhkYjJmMjcyNDRlODk0M2JhMTY4Y2Q1NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.egbVkv26yKvbHBp7yCSZ_wmcm-V9A_hcgBI8GjHn2Zw)

Thanks this looked like a specific issue with the map (which is a separate component from the graphs) not recalculating after a filter was applied.

While I was there I added your suggestion of having the grant totals in the graph/map title as that was easy to do. 

Changes now pushed to dev.

**Comment by mariongalley** [comment]
>While I was there I added your suggestion of having the grant totals in the graph/map title as that was easy to do.

@michaelwood That is amazing, thanks so much for doing that!

Do you know how come there are ~1k grants where we couldn't determine the funder or funder type? It's not the non-GBP ones is it?

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/3d163008-a0b3-417e-a610-a0db5c61476c)
