### ISSUE TITLE
Identifier not recognised bar is missing from org types chart

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#219]
Live Insights

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/0f2ed740-c15c-4cd4-821a-e0d00bc4420a)

Dev Insights

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/8c5cc44e-416a-40af-b438-911bd698112d)

Links in [live](https://insights.threesixtygiving.org/?funders=GB-SC-SC035190) and [dev](http://insights-test.360dokku1.vs.mythic-beasts.com/?fundingOrganization=GB-SC-SC035190) Insights

**Comment by KDuerden** [comment]
Could we consider renaming the title for the 360G prefixed values? In the context of a chart of organisation types, it might make more sense for it to be "Organisation type not available"

This would be different from the grants excluded because they are individual grants, so not sure how that is going to be represented (not represented) in the charts.

**Comment by mariongalley** [comment]
@KDuerden For grants that don't appear in the chart at all we should update the copy that currently says org type is not available to say something like "X grants have no recipient organisation type because they are to individuals."

**Comment by michaelwood** [comment]
Identifier not recognised:

Identifier not recognised was a quirk of the old insights where it used it's own logic rather than the datastore/grantnav, we don't normally show a bar graph for the missing data as we have an explanation and a total of items not included in the graph, there is no mechanism for doing this currently so it would need to be added to the datastore. Estimate about 1.5 day of work.

Graph titles: 

Titles: Ideally we would keep the titles consistent with the equivalent GrantNav filters so that the link is made in the person's mind between the two. In GrantNav the equivalent is called "Funding Organization Type" .

**Comment by michaelwood** [comment]
Would this work for the copy fix? -

![image](https://github.com/ThreeSixtyGiving/360insights/assets/493697/9a5bc86c-3b7e-4f46-a20d-e41a20be13f7)

**Comment by KDuerden** [comment]
thanks, I like this a lot!
