### ISSUE TITLE
Income of Recipients bands should match live

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#221]
Live

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/fce678bc-57c1-4b29-b854-d483e5451fca)

Dev

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/17f619f1-48b9-46b3-a43f-8082830957e6)

**Comment by michaelwood** [comment]
These were changed to match GrantNav/Insights's 'Award amount' bands after it was mentioned they were inconsistent.

**Comment by mariongalley** [comment]
@michaelwood That's fair enough for the Amount Awarded chart but the income of recipients chart doesn't have an analogue in GrantNav, and I think the previous banding made more sense (organisation income can be expected to be higher than grant sizes so doesn't need as many very small bands)

**Comment by michaelwood** [comment]
The insights does have the same top-band (Over £10m) as the GrantNav standard. 

For prioritisation - To have custom bands would be ~0.5 day effort because it means not being able to use the existing tested GrantNav code for the banding aggregations, preference from a technical complexity point of view would also be to live with this if possible.

**Comment by michaelwood** [comment]
New bands have been implemented. Fixes deployed.

Note slight difference as the labels use the GrantNav text format so will continue without the suffixes (apart from the manual ones "Up to" and "Over").
