### ISSUE TITLE
Age of recipient organisations in wrong order

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantvis#222]
Update new age chart is in the incorrect order, and needs to match current Insights.

**New Insights**
The chart is ordered high to low, which is unhelpful
![image](https://github.com/ThreeSixtyGiving/360insights/assets/20462640/a1e8bfc2-f8f1-4e8f-b8e9-588362a0938f)

**Current Insights**
The chart is ordered by age from newest to oldest - which is what we want to continue to have
![image](https://github.com/ThreeSixtyGiving/360insights/assets/20462640/4b6fda6b-3677-4936-a25e-49d16f961392)

**Comment by michaelwood** [comment]
This change is to match GrantNav, I believe in GrantNav it was done like this so that the ordering of the graph/filter labels is fixed in a logical order which users expect rather than using the default of ordering based on the highest number.

**Comment by KDuerden** [comment]
Recipient age isn't exposed in the front end of GrantNav, so where is this logic being applied?

The GrantNav amount awarded band is ordered in size of band, rather than by highest to lowest number of grants in each band, so is it possible to override this logic for the age bands too?

**Comment by michaelwood** [comment]
Amount awarded and Award date in GrantNav use logical ordering rather than highest amount of grants ordering.  There's a whole pile of code added in 2016 to do this exception to the way ElasticSearch handles things by default, but I couldn't find much more about the history as the commit was rather nondescript! (https://github.com/ThreeSixtyGiving/grantnav/commit/e025e7a03e3d8c94a9cf7ef6238347c5eb7df15b)

**Comment by michaelwood** [comment]
Ignore me. I misread the original issue and got dev and current the wrong way round! (if we can call them dev and live that'd be good)

**Comment by michaelwood** [comment]
This was quite a rabbit warren of a job but I believe it is now fixed (see dev)

**Comment by michaelwood** [comment]
Re-opening as this has introduced a new bug that because the top item in the graph (like most of them) isn't the largest the scale calc is now wrong.

**Comment by michaelwood** [comment]
Now fixed secondary issue

**Comment by michaelwood** [comment]
This issue took longer than expected, steps involved (briefly documented) were:

1. Look into how other fixed order labels work in GN
2. This is an exceptional one due to it being embedded in the ES index
3. Write a sort algorithm to re-sort the data into the same ordering as the list of labels
4. Spin up my local dev GrantNav to test the fix - appears to work
5. Create a branch on GrantNav https://github.com/ThreeSixtyGiving/grantnav/pull/1021
6. Test on dev grantnav
7. Issue appears not resolved
8. Automation tests on grantnav fail unconnected to change but due to timings
9. Investigate that GrantNav failed tests are due to cookie popup blocking mouse focus
10. Attempt to fix in sustainable way using a function which runs for each test to remove cookie popup ([fixture](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#autouse-fixtures-fixtures-you-don-t-have-to-request))
11. This fails to fix issue due to unknown pytest not running fixtures. Reluctant to investigate further as this is a legacy way of doing the testing.
12. Test to see if this is a browser timing issue is resolved by adding a sleep timer to wait for popup to close. This doesn't work. 
13. Setup local browser testing framework to debug the issue
14. Browser won't load due to containerisation of browser on Ubuntu OS, research, update chromedriver and set fixed dev interface ports.
15. Re-read pytest fixture documentation
16. No resolution so use existing method of on-demand cookie popup close which fixes issue
17. Back to original issue. problem deploying on Dev GrantNav as on special branch for the explore insights button to point to dev insights mw/insights_button_dev
18. Rebase that branch against mw/aggs_reorder_recipient_age_labels branch
19. Try reload on local and find out that local test data now coincidentally has the correct ordering because of the number of orgs in each label due to being reloaded due to data needed for earlier browser testing
20. Find out assignment of final ordered value is not being modified. Fix this.
21. git cherry-pick temp insights explore button from old branch to new one
22. PR now in limbo state but branch deployed to dev
23. Change not working on dev, restart dev, dev now working
24. Verify Fixed
25. Note issue problem due to top bar item not being max size of number of orgs making the scale go wrong
26. Reopen
27. Add exception to the graph scale max value calculation
28. Redeploy insights test
29. Note grantnav test data doesn't fail because it also has coincidentally the correct ordering 
30. Fixed

approx 1 day
