### ISSUE TITLE
Add feature to configure title for different custom insights

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#227]
Add a config item to configure the title for the version of insights that we're using.

Position/style of the title needs to be decided as its a slightly different layout to the original covid/col trackers.

Couple of options:

## Option 1

![image](https://github.com/ThreeSixtyGiving/360insights/assets/493697/7150a45b-bf8f-42ae-8355-b8f7aba520b3)

## Option 2

![image](https://github.com/ThreeSixtyGiving/360insights/assets/493697/26c847b0-71ce-48f1-b4f9-a57731d88348)

If it's easier to jump on a call, I can move the title and its style around to our hearts content

**Comment by michaelwood** [comment]
This should also update the site title. 
```html
  <title>360Insights</title>
```

**Comment by mariongalley** [comment]
Thanks @michaelwood , I guess the main problem is the big ol' Insights logo. While it is in some sense 'an Insights product', I think it will confuse users. For the Quality Dashboard we made a version of the logo with the product name, but I don't think this will work for the CoL tracker as the name is way too long.

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/3558a49d-bb21-4c45-9ad2-621890eee1eb)

I suggest we do what we did on the live Covid tracker, which is a version of Option 1 but changing to a plain 360Giving logo rather than using the 360Insights logo.

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/be9469f5-3049-48ca-b886-c23d6e6f7c58)

I guess my preferred solution would be something more akin to what's on the live CoL tracker, where David made a skinny version of the kicker to get rid of some of the unusable white space. So that's more like Option 2 but without the huge kicker:

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/16b0f0ac-04c1-4923-a83f-608882928a1f)

Would that be possible?

**Comment by michaelwood** [comment]
>
> I suggest we do what we did on the live Covid tracker, which is a version of Option 1 but changing to a plain 360Giving logo rather than using the 360Insights logo.
> 
> ![image](https://private-user-images.githubusercontent.com/82958988/297410418-be9469f5-3049-48ca-b886-c23d6e6f7c58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MjcxMTUsIm5iZiI6MTcwNTUyNjgxNSwicGF0aCI6Ii84Mjk1ODk4OC8yOTc0MTA0MTgtYmU5NDY5ZjUtMzA0OS00OGNhLWI4ODYtYzIzZDZlNmY3YzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDIxMjY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNDI5MDA4NmM1MzJjNDMyMTVmMjg4MGFkYmFhN2E2YWIzY2VmYTM4YmJhNDkyYjllMzc3MzEyOTBhZGNmNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hLY026Ni_klKiFub3hDmpfoPueIilgkGkxSog_SeqeA)
> 
> I guess my preferred solution would be something more akin to what's on the live CoL tracker, where David made a skinny version of the kicker to get rid of some of the unusable white space. So that's more like Option 2 but without the huge kicker:
> 

Changing the page template of Insights depending on the version/skew is quite a lot of design & implementation work not just because it needs to be dynamic based on the config but also as the kicker is used to show funder and date filter information such as 
"Grants made by:
The National Lottery Community Fund between 2022 and 2023"

We can do the logo change quite easily though.

How about option 3:

![image](https://github.com/ThreeSixtyGiving/360insights/assets/493697/85af7fa8-e47c-423e-bcdb-19583d4cd6fe)

This is logo swapable + "Grants made by" as a lower level heading + dynamic title ?

**Comment by mariongalley** [comment]
@michaelwood Yes, happy with this thank you. Can we lose the semicolon after "grants made by" please?

**Comment by michaelwood** [comment]
Done and now deployed to dev
