### ISSUE TITLE
Keyword searches passed from GrantNav to Insights insufficiently sticky

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#231]
**Describe the issue**
If you configure a search in GrantNav which includes keywords and then open it in Insights, sometimes if you add a filter in Insights, the keyword part of the query gets lost from the selection - although sometimes it doesn't. Also the terms themselves aren't included in the url.

**Steps to reproduce the error**

- [GrantNav search with keyword filter children & young people + some filters = 554 grants](https://grantnav.threesixtygiving.org/search?query=children+OR+%22young+people%22&default_field=title_and_description&sort=awardDate+desc&min_date=01%2F2022&recipientRegionName=Wales&fundingOrganizationTSGType=Grantmaking+Organisation&fundingOrganizationTSGType=Lottery+Distributor&recipientTSGType=Organisation).
-  [If you open in Insights then filter to grants under £50k, the results then have 2668 grants](https://insights.threesixtygiving.org/?min_date=01%2F2022&recipientRegionName=Wales&fundingOrganizationTSGType=Grantmaking+Organisation&fundingOrganizationTSGType=Lottery+Distributor&recipientTSGType=Organisation&max_amount=50000), indicating some filtering has been lost, and if you then view this in GrantNav you can see the keyword terms have been wiped
- But if you instead filter by location, eg Cardiff, the results update as they should, and you see 74 grants (can't provide a link as it doesn't include the keywords so returns a different number of results, so you'll have to follow the steps), and if you click back to GrantNav from there, the keyword search is still in place.

Note: If you filter using the award size chart rather than the min/max bit, it seems to keep the text filters and shows the correct values ok, so could be specific to these elements.

**Comment by michaelwood** [comment]
notes:

This is due to the `query` parameter being deleted from the visible URL query which was added to make sure that configured insights instances such as COL don't have their GrantNav query edited by the users.

https://github.com/ThreeSixtyGiving/360insights/blob/live/insights/static/js/data-display.js#L81

We can make this conditional based on whether we have a configured/set query for the instance of insights. This is also related to "Saved searches" idea for GrantNav, as this would be the better way to create a fixed search that can be then used by insights.

**Comment by michaelwood** [comment]
Deployed :rocket:

**Comment by mariongalley** [comment]
@michaelwood Is this deployed in live? I just tested the example from the description and I still found the same thing, where adding filtering by amount once the search is opened in Insights seems to clear the keyword filtering
