### ISSUE TITLE
Font too light / difficult to read

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantvis#58]
The font, especially for italics in explanations is too light and therefore difficult to read.

It is slightly worse on Chrome 

![image](https://user-images.githubusercontent.com/20462640/151413067-d26ea4a0-8526-4b60-8174-27ba7c669b4d.png)

vs Firefox.

![image](https://user-images.githubusercontent.com/20462640/151413119-ff12004b-222f-44a5-bf00-23c09bc3b215.png)

Font weight and/or size need to be increased to aid accessibility.

**Comment by michaelwood** [comment]
Hmm this is interesting... The fonts across the design system do look very different in firefox vs chrome for me as well, chrome seems to ignore reducing `font-weight` making the fonts appear differently.
https://cdn.threesixtygiving.org/components/detail/typography.html

Which is in use for example: https://cdn.threesixtygiving.org/components/detail/insights--detail.html looks like this for me in firefox:

![Screenshot 2022-01-28 at 10-25-50 Insights Detail 360Giving Design System - Components](https://user-images.githubusercontent.com/493697/151531067-c78e5fea-0418-4712-9b0f-36a3258630fb.png)

and this in chromium:

![Screenshot from 2022-01-28 10-23-35](https://user-images.githubusercontent.com/493697/151531235-afef4938-8cdb-431a-9c74-4ba07d653186.png)

I think the job here is looking at design system https://cdn.threesixtygiving.org and trying to work out a solution there so that all the other sites will also not have this issue.

**Comment by KDuerden** [comment]
Thanks @michaelwood 
The font weight on the dev dashboard and even the [Covid grants tracker](https://covidtracker.threesixtygiving.org/) don't have the above problem for me, but not sure what's different about those in terms of design system or tech.

**Comment by michaelwood** [comment]
Yeah, It's effectively just different text or components in use, e.g. the small text under a graph was an insights specific one but the design system does contain other non-product specific components. I've raised an issue on the design system which lists the components which are likely to cause problems https://github.com/ThreeSixtyGiving/360-ds/issues/51.

**Comment by michaelwood** [comment]
Looks like there is a custom bit of CSS for text under graphs. We can remove this customisation and use a standard text. This is the part needing fixing for live. The 360 -ds stuff is somewhat out of scope.

**Comment by michaelwood** [comment]
Removed the custom text styling and added an horizontal divider to make it distinct as present in dashboard design.

![Screenshot from 2022-02-02 12-28-51](https://user-images.githubusercontent.com/493697/152153745-01b1f022-a13a-46ca-9503-c334271f4b91.png)

**Comment by KDuerden** [comment]
As discussed yesterday, here is my browser set up.

Chrome Version 98.0.4758.82 (Official Build) (64-bit)

Dell laptop System 
Processor	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
Installed RAM	16.0 GB (15.9 GB usable)
System type	64-bit operating system, x64-based processor

Edition	Windows 10 Pro
Version	21H1
Installed on	‎20/‎08/‎2020
OS build	19043.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0

Here is what is says about style when I inspect element for the light/italics text.

![image](https://user-images.githubusercontent.com/20462640/152158567-e367f05f-f88b-4b23-8857-55a334c2b58b.png)

Let me know if I'm looking at the wrong bit or you need to me copy anything else.

**Comment by michaelwood** [comment]
@KDuerden Thanks that's just what is needed.

I think we should have resolved this now by using a different font style in the chart area. http://insights-ng.insightsng.vs.mythic-beasts.com/data?funders=GB-CHC-1080418 (e.g. see Recipient type)

Closing for now

**Comment by KDuerden** [comment]
Yes that worked

![image](https://user-images.githubusercontent.com/20462640/152208617-b0e9d6c0-dcbf-4eae-96f5-5c663a03d352.png)
