### ISSUE TITLE
General: minor layout/copy changes

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#70]
- In order to reduce the white space and because it doesn't add much value, could we get rid of "Select a 360Giving dataset" at the top and move everything up into that vacated space?

![image](https://user-images.githubusercontent.com/82958988/151584985-89bf3da6-804b-4197-bab4-fb0ec2aa7228.png)

- On the results page, I'm not sure the copy at the top is that helpful/clear
    - "This data contains grants made in 2 different currencies. Only showing grants made in GBP." I think this should be in the "error message/warning" box style so that people understand it's a caveat about the visualisations
    - Do we need "From the 360Giving data registry" to be here so prominently? I think we could lose it altogether, or move it to the Data Sources box at the bottom of the home/landing page.
- Could we make the Insights logo bigger on the results page, more like the initial landing page?
- Is there any way we could make it have less white space/more colour? I guess we're limited by what's available in the Design system, but the existing version of Insights had that vertical blue bar on the left on the results page which made it less of a vast white expanse (and a horizontal red bar on the initial landing page, though I don't like the red)
- Can we turn all text based links into Buttons like we're doing for the GrantNav link? I found almost all of them very difficult to spot, including the registry link, the map links at the bottom of the graphs, the "more about data sources" link. 
    - Where it does need to be an inline link like "Charity data is sourced from **findthatcharity.uk** and postcode data from **postcodes.findthatcharity.uk**. Company data is fetched using Companies House URIs. All external data is used under the **Open Government Licence**." I think the links need to be more visually distinct as they're very hard to spot. Perhaps a lighter colour, or underlined? Is this what's in the design system?
- Why does "Average Grant" have an asterisk in the headline stats? I can't see where I'm meant to go to read the related note
- Should we spell out URI or is it like API and spelling it out doesn't help at all if you don't already know what it is?

**Comment by michaelwood** [comment]
Checklist of the above:

- [x] In order to reduce the white space and because it doesn't add much value, could we get rid of "Select a 360Giving dataset" at the top and move everything up into that vacated space? On the results page, I'm not sure the copy at the top is that helpful/clear
- [x] "This data contains grants made in 2 different currencies. Only showing grants made in GBP." I think this should be in the "error message/warning" box style so that people understand it's a caveat about the visualisations
- [x] Do we need "From the 360Giving data registry" to be here so prominently? I think we could lose it altogether, or move it to the Data Sources box at the bottom of the home/landing page.
- [x] Could we make the Insights logo bigger on the results page, more like the initial landing page?
- [ ] Is there any way we could make it have less white space/more colour? I guess we're limited by what's available in the Design system, but the existing version of Insights had that vertical blue bar on the left on the results page which made it less of a vast white expanse (and a horizontal red bar on the initial landing page, though I don't like the red)
- [x] Can we turn all text based links into Buttons like we're doing for the GrantNav link? I found almost all of them very difficult to spot, including the registry link, the map links at the bottom of the graphs, the "more about data sources" link.
- [x] Where it does need to be an inline link like "Charity data is sourced from findthatcharity.uk and postcode data from postcodes.findthatcharity.uk. Company data is fetched using Companies House URIs. All external data is used under the Open Government Licence." I think the links need to be more visually distinct as they're very hard to spot. Perhaps a lighter colour, or underlined? Is this what's in the design system?
- [x] Why does "Average Grant" have an asterisk in the headline stats? I can't see where I'm meant to go to read the related note
- [x] Should we spell out URI or is it like API and spelling it out doesn't help at all if you don't already know what it is?

**Comment by BibianaC** [comment]
@mariongalley if we make the logo on the results page as big as the one on the homepage would be like this:

<img width="1082" alt="Screen Shot 2022-02-04 at 16 27 36" src="https://user-images.githubusercontent.com/9610927/152566913-9ca14f28-e099-44c0-bcb3-22c978bbd9bc.png">

Is this how you would like it? or would you also want to change the titles to be next to the logo as in the homepage?

**Comment by mariongalley** [comment]
Feedback from the comms team is that they like how big it is, but it does create a lot of additional white space at the top.

Would it be possible for the "Grants made by 360Giving publishers" page heading to be on the same line as the logo so that it fills that space @BibianaC ?

**Comment by BibianaC** [comment]
@mariongalley I have created the PR https://github.com/ThreeSixtyGiving/insights-ng/pull/96

**Comment by mariongalley** [comment]
Note: Remaining unchecked items not as big a priority now except making the links more visible

**Comment by BibianaC** [comment]
@mariongalley regarding making `Data Sources` links more visible:

<img width="1011" alt="Screen Shot 2022-02-14 at 10 28 54" src="https://user-images.githubusercontent.com/9610927/153847029-dadb7407-01a3-4abe-8030-91436a3031a8.png">

**Comment by BibianaC** [comment]
@mariongalley the only issue left on this ticket is

`
Is there any way we could make it have less white space/more colour? I guess we're limited by what's available in the Design system, but the existing version of Insights had that vertical blue bar on the left on the results page which made it less of a vast white expanse (and a horizontal red bar on the initial landing page, though I don't like the red)
`
Insights, the Registry, and the Dashboard have the same white space. If we make changes in one of the three, we might also want to change the other two. It might be good to close this issue and open a new one in `360-ds`

**Comment by mariongalley** [comment]
Yes, happy to close this. I think that's something we could discuss if we ever get a designer too look at Insights but not really required.
